window.SHIRT_PRODUCTS = [
    {
        id: "coda-led-zeppelin",
        name: "CODA Led Zeppelin Baseball Tee",
        tagline: "Black body / white raglan sleeve",
        description: "A fitted vintage baseball tee with a bold CODA Led Zeppelin front print and clean contrast sleeves.",
        price: 32,
        image: "shirt-images/coda-led-zeppelin-front-v4.webp",
        backImage: "shirt-images/coda-led-zeppelin-back-v4.webp",
        alt: "CODA Led Zeppelin baseball tee front",
        backAlt: "CODA Led Zeppelin baseball tee back",
        background: "#d8dedc",
        imageFit: "cover",
        imagePosition: "center",
        imagePadding: "0",
        sizes: ["S", "M", "L", "XL", "2XL"]
    },
    {
        id: "wings-yellow-red",
        name: "Wings Yellow and Red Baseball Tee",
        tagline: "Mustard body / red raglan sleeve",
        description: "A warm yellow and red long-sleeve baseball tee with a vintage Wings-style front graphic.",
        price: 34,
        image: "shirt-images/wings-yellow-red-front-v4.webp",
        backImage: "shirt-images/wings-yellow-red-back-v4.webp",
        alt: "Wings yellow and red baseball tee front",
        backAlt: "Wings yellow and red baseball tee back",
        background: "#f1e7c6",
        imageFit: "cover",
        imagePosition: "center",
        imagePadding: "0",
        sizes: ["S", "M", "L", "XL", "2XL"]
    },
    {
        id: "rolling-stones-white",
        name: "The Rolling Stones White Tee",
        tagline: "White short sleeve tee",
        description: "A crisp white tee with the classic tongue graphic up front and a clean blank back view.",
        price: 30,
        image: "shirt-images/rolling-stones-white-front-v4.webp",
        backImage: "shirt-images/rolling-stones-white-back-v4.webp",
        alt: "The Rolling Stones white tee front",
        backAlt: "The Rolling Stones white tee back",
        background: "#d8d8d8",
        imageFit: "cover",
        imagePosition: "center",
        imagePadding: "0",
        sizes: ["S", "M", "L", "XL", "2XL"]
    }
];
