window.SHIRT_PRODUCTS = [
    {
        id: "coda-led-zeppelin",
        name: "CODA Led Zeppelin Baseball Tee",
        tagline: "Black body / white raglan sleeve",
        description: "A fitted vintage baseball tee with a bold CODA Led Zeppelin front print and clean contrast sleeves.",
        price: 32,
        image: "shirt-images/coda-led-zeppelin-front-v5.webp",
        backImage: "shirt-images/coda-led-zeppelin-back-v5.webp",
        alt: "CODA Led Zeppelin baseball tee front",
        backAlt: "CODA Led Zeppelin baseball tee back",
        background: "#d8dedc",
        imageFit: "cover",
        imagePosition: "center",
        imagePadding: "0",
        sizes: ["S", "M", "L", "XL", "2XL"],
        fit: "Fitted baseball tee. Size up for a looser vintage merch-table feel.",
        fabric: "Soft cotton-blend black body with white raglan sleeves.",
        turnaround: "Made to order. Usually ready to ship in 5-10 business days.",
        care: "Wash cold inside out. Tumble dry low. Do not iron directly over print."
    },
    {
        id: "wings-yellow-red",
        name: "Wings Yellow and Red Baseball Tee",
        tagline: "Mustard body / red raglan sleeve",
        description: "A warm yellow and red long-sleeve baseball tee with a vintage Wings-style front graphic.",
        price: 34,
        image: "shirt-images/wings-yellow-red-front-v5.webp",
        backImage: "shirt-images/wings-yellow-red-back-v5.webp",
        alt: "Wings yellow and red baseball tee front",
        backAlt: "Wings yellow and red baseball tee back",
        background: "#f1e7c6",
        imageFit: "cover",
        imagePosition: "center",
        imagePadding: "0",
        sizes: ["S", "M", "L", "XL", "2XL"],
        fit: "Classic long-sleeve raglan fit with a straight body.",
        fabric: "Soft mustard body with red raglan sleeves and a vintage-style front print.",
        turnaround: "Made to order. Usually ready to ship in 5-10 business days.",
        care: "Wash cold inside out. Tumble dry low. Keep bleach far away."
    },
    {
        id: "rolling-stones-white",
        name: "The Rolling Stones White Tee",
        tagline: "White short sleeve tee",
        description: "A crisp white tee with the classic tongue graphic up front and a clean blank back view.",
        price: 30,
        image: "shirt-images/rolling-stones-white-front-v5.webp",
        backImage: "shirt-images/rolling-stones-white-back-v5.webp",
        alt: "The Rolling Stones white tee front",
        backAlt: "The Rolling Stones white tee back",
        background: "#d8d8d8",
        imageFit: "cover",
        imagePosition: "center",
        imagePadding: "0",
        sizes: ["S", "M", "L", "XL", "2XL"],
        fit: "Easy short-sleeve tee fit. True to size for most buyers.",
        fabric: "Crisp white cotton-feel tee with a bold front graphic.",
        turnaround: "Made to order. Usually ready to ship in 5-10 business days.",
        care: "Wash cold inside out. Tumble dry low to keep the print fresh."
    }
];
